-- begin CUBATRAININGTASK_EMPLOYEE
alter table CUBATRAININGTASK_EMPLOYEE add constraint FK_CUBATRAININGTASK_EMPLOYEE_CENTER foreign key (CENTER_ID) references CUBATRAININGTASK_CAR_SERVICE_CENTER(ID)^
create index IDX_CUBATRAININGTASK_EMPLOYEE_CENTER on CUBATRAININGTASK_EMPLOYEE (CENTER_ID)^
-- end CUBATRAININGTASK_EMPLOYEE
-- begin CUBATRAININGTASK_CAR_SERVICE_CENTER_CITY_LINK
alter table CUBATRAININGTASK_CAR_SERVICE_CENTER_CITY_LINK add constraint FK_CARSERCENCIT_CAR_SERVICE_CENTER foreign key (CAR_SERVICE_CENTER_ID) references CUBATRAININGTASK_CAR_SERVICE_CENTER(ID)^
alter table CUBATRAININGTASK_CAR_SERVICE_CENTER_CITY_LINK add constraint FK_CARSERCENCIT_CITY foreign key (CITY_ID) references CUBATRAININGTASK_CITY(ID)^
-- end CUBATRAININGTASK_CAR_SERVICE_CENTER_CITY_LINK
-- begin CUBATRAININGTASK_INDIVIDUAL
alter table CUBATRAININGTASK_INDIVIDUAL add constraint FK_CUBATRAININGTASK_INDIVIDUAL_ID foreign key (ID) references CUBATRAININGTASK_CUSTOMER(ID)^
-- end CUBATRAININGTASK_INDIVIDUAL
-- begin CUBATRAININGTASK_COMPANY
alter table CUBATRAININGTASK_COMPANY add constraint FK_CUBATRAININGTASK_COMPANY_ID foreign key (ID) references CUBATRAININGTASK_CUSTOMER(ID)^
-- end CUBATRAININGTASK_COMPANY
